print("welcome to this page")
name=input()
print("hello",name)
print("so",name,"how  old are you")
age=input()
age=int(age)
print("your age is",age)
bin_age=bin(age)
print("so next year you will be",age+1)
print("you know you binary yoyr age is",bin_age)